{{- if not .Values.settings.gitbaseServer }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitbase-playground.fullname" . }}-clone-git-repositories
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  clone-git-repositories.sh: |
    # Quick and dirty way to have the same state in case of multiple replicas
    # if a certain commit is given per repository
    set -x
    cd {{ .Values.gitbaseServer.repositoriesDir }}
    {{- range $name, $config := .Values.gitbaseServer.repositories }}
    {{- $url := required "Missing url in repo" $config.url }}
    {{- $commit := default "HEAD" $config.commit }}
    if [ ! -d "{{ $name }}" ]; then
      git clone {{ $url }} {{ $name }}
    fi
    cd {{ $name }}
    git pull
    git reset --hard {{ $commit }}
    cd ..
    {{- end }}
{{- end }}
