apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-data-dir=/var/lib/cert-manager"
            # We only support googlecloud for the moment in this chart
            - "-default-provider=googlecloud"
            - "-acme-url={{ .Values.args.acmeUrl }}"
            {{ if .Values.args.class }}
            # You can run multiple instances of kube-cert-manager for the same namespace(s),
            # each watching for a different value for the 'class' label
            - "-class={{ .Values.args.class }}"
            {{ end }}
            {{ if .Values.args.namespaces }}
            # You can choose to monitor only some namespaces, otherwise all namespaces will be monitored
            "-namespaces={{ .Values.args.namespaces }}"
            {{ end }}
            # If you set a default email, you can omit the field/annotation from Certificates/Ingresses
            {{ if .Values.args.defaultEmail }}
            - "-default-email={{ .Values.args.defaultEmail }}"
            {{ end }}
            {{ if .Values.args.renewBeforeDays }}
            - "-renew-before-days={{ .Values.args.renewBeforeDays }}"
            {{ end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
            - name: google-application-credentials
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: GCE_PROJECT
              value: {{ required "Missing google project" .Values.google.project }}
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
        - name: google-application-credentials
          secret:
            secretName: {{ template "fullname" . }}-google-key

