kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "k8s-pod-headless-service-operator.fullname" . }}
  labels:
    app: {{ template "k8s-pod-headless-service-operator.name" . }}
    chart: {{ template "k8s-pod-headless-service-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "k8s-pod-headless-service-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "k8s-pod-headless-service-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "k8s-pod-headless-service-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ required "missing image.tag" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if  .Values.app.podAnnotation }}
            - name: POD_ANNOTATION
              value: {{ .Values.app.podAnnotation }}
            {{- end }}
            {{- if  .Values.app.namespace }}
            - name: NAMESPACE
              value: {{ .Values.app.namespace }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
