{{- if not .Values.settings.serverAddr }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      # This is to upgrade the deployment if configmap changes
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/install-bblfshd-drivers-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      {{- if .Values.server.drivers.install }}
      volumes:
        - configMap:
            name: install-bblfshd-drivers
            items:
            - key: install-bblfshd-drivers.sh
              path: install-bblfshd-drivers.sh
          name: install-bblfshd-drivers-volume
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -bblfsh-addr=localhost:9432
        resources:
{{ toYaml .Values.resources | indent 10 }}
      - name: bblfshd
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        {{- if .Values.server.drivers.install }}
        volumeMounts:
          - name: install-bblfshd-drivers-volume
            mountPath: /opt/install-bblfshd-drivers.sh
            subPath: install-bblfshd-drivers.sh
        lifecycle:
          postStart:
            exec:
              command: [ "sh", "/opt/install-bblfshd-drivers.sh" ]
        {{- end }}
        securityContext:
          privileged: true
        resources:
{{ toYaml .Values.server.resources | indent 10 }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
