# Default values for borges.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/srcd/borges
  # This value should be provided when releasing this chart
  # tag: v0.16.2
  pullPolicy: IfNotPresent
consumer:
  workers: 12
  loglevel: info
  timeout: 2h
  profiler: false
  profilerPort: 6061
  metrics: true
  metricsPort: 6062
  sysdigConfig: true
  bucketSize: 2
  replicaCount: 1
  cleanTmp: true
  logformat: json
  # fluenbitParser: docker_json

producer:
  loglevel: info
  profiler: false
  profilerPort: 6061
  metrics: true
  metricsPort: 6062
  sysdigConfig: true
  replicaCount: 1
  logformat: json
  # fluenbitParser: docker_json

republish:
  # Use 0 to do a one time republish. Add a time unit prefix to specify
  # cycle time (s = seconds, m = minutes, h = hours).
  cycle: 1h
  # Time in milliseconds to wait for a new job.
  timeout: 500
  loglevel: info
  profiler: false
  profilerPort: 6061
  metrics: true
  metricsPort: 6062
  replicaCount: 1
  logformat: json
  # fluenbitParser: docker_json

broker:
  connectionString: amqp://guest:guest@rabbitmq:5672
  jobsQueue: borges
  mentionsQueue: rovers

db:
  user: testing
  pass: testing
  host: postgres
  name: testing

dir:
  tmp: /borges-tmp/tmp
  rootRepositories: /borges/root-repositories
  rootRepositoriesTemp: /borges/tmp

#hadoop:
#  userName: root
#  connectionString: hdfs-namenode:8020

#glusterfs:
#  endpoints: glusterfs-cluster
#  volume: siva-volume

locking:
  connectionString: etcd:http://etcd:2379

#nodeSelector:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
