apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    app: {{ template "name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-spark-master"
spec:
  replicas: {{ default 1 .Values.master.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-spark-master"
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        component: "{{ .Release.Name }}-spark-master"
    spec:
      volumes:
      {{- with .Values.master.additionalVolumes  }}
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.livy.enabled }}
        - name: config
          configMap:
            name: {{ template "master-fullname" . }}-livy-conf
      {{- end}}
      containers:
        - name: {{ template "master-fullname" . }}
          image: "{{ .Values.master.image }}:{{ .Values.master.imageTag }}"
          imagePullPolicy: {{ .Values.master.imagePullPolicy }}
          command: 
            - /bin/sh
            - -c
            - |
              echo $(hostname -i) {{ template "master-fullname" . }} >> /etc/hosts
              /opt/spark/sbin/start-master.sh --host {{ template "master-fullname" . }} --port 7077 --webui-port 8998
          ports:
            - name: master
              containerPort: 7077
            - name: webui
              containerPort: 8998
          volumeMounts:
          {{- with .Values.master.additionalVolumeMounts  }}
{{ toYaml . | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.master.resources | indent 12 }}
          env:
          - name: SPARK_DAEMON_MEMORY
            value: {{ default "1g" .Values.master.daemonMemory | quote }}
          - name: SPARK_NO_DAEMONIZE
            value: "yes"
          {{- with .Values.master.extraEnv  }}
{{ toYaml . | indent 10 }}
          {{- end }}
      {{- if .Values.livy.enabled }}
        - name : {{ template "livy-fullname" . }}
          image: "{{ default "srcd/spark-livy" .Values.livy.image }}:{{ default "2.2.3" .Values.livy.ImageTag }}"
          ports:
            - name: livy
              containerPort: 8998
          volumeMounts:
            - mountPath: /opt/livy/conf/livy.conf
              name: config
              subPath: livy.conf
      {{- end }}
      affinity:
{{ toYaml .Values.master.affinity | indent 8 }}
    {{- with .Values.master.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
