apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spark-thrift-server.fullname" . }}
  labels:
    app: {{ template "spark-thrift-server.name" . }}
    chart: {{ template "spark-thrift-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "spark-thrift-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "spark-thrift-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/spark-2.3.2-bin-hadoop2.7/bin/spark-submit
            - --master
            - {{ required "Missing app.sparkMasterURI" .Values.app.sparkMasterURI | quote }}
            {{- if .Values.app.executorCores }}
            - --conf
            - spark.executor.cores={{ .Values.app.executorCores }}
            {{- end }}
            {{- if .Values.app.maxCores }}
            - --conf
            - spark.cores.max={{ .Values.app.maxCores}}
            {{- end }}            
            - --conf
            - "spark.datasource.gitbase.user={{ .Values.app.gitbaseUser }}"
            - --conf
            - "spark.datasource.gitbase.password=$(GITBASE_PASSWORD)"
            - --conf
            - "spark.driver.host=$(POD_IP)"
            - --conf
            - "spark.datasource.gitbase.urls={{ required "Missing app.gitbaseServers" .Values.app.gitbaseServers }}"
            - --conf
            - "spark.datasource.gitbase.bblfsh.host={{ required "Missing app.bblfshHost" .Values.app.bblfshHost }}"
            - --conf
            - "spark.datasource.gitbase.bblfsh.port={{ .Values.app.bblfshPort }}"
            - --class
            - tech.sourced.gitbase.spark.StartThriftServer
            - --packages
            - org.postgresql:postgresql:42.2.5
            - /opt/jars/gitbase-spark-connector-enterprise-uber.jar
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GITBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: "{{ default (include "spark-thrift-server.gitbase.secretName" .) .Values.app.gitbasePasswordSecretName }}"
          ports:
            - name: thrift
              containerPort: 10000
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: thrift
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: thrift
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
