apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lookout.fullname" . }}-lookout-configuration
  labels:
    app: {{ template "lookout.name" . }}
    chart: {{ template "lookout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    analyzers:
    {{- with .Values.analyzers }}
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.providers }}
    providers:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.repositories }}
    repositories:
{{ toYaml . | indent 6 }}
    {{- end }}
