apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-agent
  labels:
    app: {{ template "fullname" . }}-agent
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.agent.num_instances }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-agent
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}-agent
        image: "{{ .Values.image.registry }}/{{ .Values.image.org }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "agent"
        env:
          - name: DRONE_SERVER
            value: ws://{{ template "fullname" . }}:{{ .Values.service.http.externalPort }}/ws/broker
          - name: DRONE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: drone_secret
          {{ range $key, $value := .Values.agent.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{ end }}
        resources:
{{ toYaml .Values.agent.resources | indent 10 }}
        volumeMounts:
          # Docker outside of Docker approach
          - mountPath: /var/run/docker.sock
            name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
