# Default values for bblfsh-web
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: bblfsh/web
  #tag: v0.8.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  internalPort: 8080

ingress:
  enabled: true
  # globalStaticIpName must be received as a parameter
  # hostname must be received as a parameter
  # hosts defined in templates/ingress.yml. Do not override here.
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.global-static-ip-name is defined in templates/ingress.yml. Do not override here.
  tls: true
    # secretName and hosts are defined in templates/ingress.yml. Do not override here.

bblfshd-sidecar:
  image:
    tag: v2.9.1

settings:
  ## serverAddr is the address to a bblfsh server, if empty a bblfsh server
  ## will be deployed by this chart. This server is deployed as a container
  ## inside of the main pod, so if multiple replicas are configured multiple
  ## bblfsh servers will be deployed
  serverAddr:
resources: {}

nodeSelector: {}

affinity: {}

# configuration for build-in server if, settings.serverAddr is empty.
server:
  image:
    repository: bblfsh/bblfshd
    tag: latest
    pullPolicy: IfNotPresent
  drivers:
    install: true
    languages:
      python:
        repository: bblfsh/python-driver
        tag: latest
      java:
        repository: bblfsh/java-driver
        tag: latest
      php:
        repository: bblfsh/php-driver
        tag: latest
      ruby:
        repository: bblfsh/ruby-driver
        tag: latest
      javascript:
        repository: bblfsh/javascript-driver
        tag: latest
      typescript:
        repository: bblfsh/typescript-driver
        tag: latest
      bash:
        repository: bblfsh/bash-driver
        tag: latest
      go:
        repository: bblfsh/go-driver
        tag: latest
  resources: {}
