# Default values for kube-cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
installCertificateType: true
image:
  repository: quay.io/srcd/kube-cert-manager
  tag: v0.5.0-srcd-1
  pullPolicy: IfNotPresent
args:
  staging: true
