apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-producer
  labels:
    app: {{ template "name" . }}-producer
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-producer
        release: {{ .Release.Name }}
      {{- if .Values.producer.fluentbitParser }}
      annotations:
        logging.parser: {{ .Values.producer.fluentbitParser }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ required "Missing borges image tag" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - borges
            - producer
            - mentions
            {{- if .Values.broker.mentionsQueue }}
            - --queue-mentions={{ .Values.broker.mentionsQueue }}
            {{- end }}
            {{- if .Values.broker.jobsQueue }}
            - --queue={{ .Values.broker.jobsQueue }}
            {{- end }}
            {{- if .Values.producer.profiler }}
            - --profiler-http
            - --profiler-port={{ .Values.producer.profilerPort }}
            {{- end }}
            {{- if .Values.producer.metrics }}
            - --metrics
            - --metrics-port={{ .Values.producer.metricsPort }}
            {{- end }}

          ports:
            {{- if .Values.producer.profiler }}
            - containerPort: {{ .Values.producer.profilerPort }}
            {{- end }}
            {{- if .Values.producer.metrics }}
            - containerPort: {{ .Values.producer.metricsPort }}
            {{- end }}
          env:
            - name: BORGES_BROKER
              value: "{{ .Values.broker.connectionString }}"
            - name: BORGES_DATABASE
              value: "{{ .Values.db.connectionString }}"
            - name: LOG_LEVEL
              value: "{{ .Values.producer.loglevel }}"
            - name: LOG_FORMAT
              value: "{{ .Values.producer.logformat }}"
            {{- if .Values.producer.sysdigConfig }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SYSDIG_AGENT_CONF
              value: |
                {
                  "app_checks": [
                    {
                      "name": "borges-producer",
                      "check_module": "go_expvar",
                      "pattern": {
                        "comm": "borges",
                        "arg": "producer"
                      },
                      "conf": {
                        "expvar_url": "http://$(POD_IP):{{ .Values.producer.metricsPort }}/debug/vars",
                        "metrics": [
                          { "path": "repos_produced", "type": "rate", "alias": "borges.producer.repos.produced" },
                          { "path": "repos_produced_failed", "type": "rate", "alias": "borges.producer.repos.produced_failed" }
                        ]
                      }
                    }
                  ]
                }
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
